version: '3.4'

services:
  dockerdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 8002:1433 
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Passdb@123456
     - MSSQL_PID=Evaluation
    # volumes:
    #   - E:/SampleCode/database:/var/opt/mssql
  docker_redis:
    container_name: redis-db
    image: redis:latest
    ports:
     - 8001:6379
  dockercomposesample:
    container_name: docker-compose-sample
    image: ${DOCKER_REGISTRY-}dockercomposesample
    build:
      context: .
      dockerfile: DockerComposeSample/Dockerfile
    ports:
     - 8003:80
    depends_on:
     - dockerdb
     - docker_redis 
    environment:
     - DB_HOST=dockerdb
     - DB_NAME=DockerSample
     - DB_SA_PASSWORD=Passdb@123456
     - DB_REDIS_HOST=docker_redis
