version: '3.4'

networks:
  backend:

services:
  dockerdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 8002:1433 
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Passdb@123456
     - MSSQL_PID=Evaluation
    # volumes:
    #   - E:/SampleCode/database:/var/opt/mssql
    networks:
     - backend

  dockercomposesample:
    container_name: docker-compose-sample
    image: ${DOCKER_REGISTRY-}dockercomposesample
    build:
      context: .
      dockerfile: DockerComposeSample/Dockerfile
    # ports:
    #  - 8001:80
    depends_on:
     - dockerdb
    environment:
     - DB_HOST=dockerdb
     - DB_NAME=DockerSample
     - DB_SA_PASSWORD=Passdb@123456
     - DB_REDIS_HOST=docker_redis
    networks:
     - backend

  docker_redis:
    container_name: redis-db
    image: redis:latest
    ports:
     - 8004:6379
    networks:
     - backend

  dockercomposesampleredis:
    container_name: docker-compose-sample-redis
    image: ${DOCKER_REGISTRY-}dockercomposesampleredis
    build:
      context: ../DockerComposeSampleRedis
      dockerfile: Dockerfile
    # ports:
    #  - 8003:80
    depends_on:
     - docker_redis 
    environment:
     - DB_REDIS_HOST=docker_redis
    networks:
     - backend

  gateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: Gateway
      dockerfile: Dockerfile
    ports:
     - 8888:80 
    networks:
     - backend